@startuml
' ==================== Metadata ====================
' @category: data-processing
' @tags: #kafka, #database, #spark, #imvu, #elasticsearch
' @application: IMVU
' @tech-stack: Kafka, Spark, Elasticsearch, Grafana
' @pattern: Architecture
' @description: Imvu Elasticsearch Architecture Diagram
' ==================================================

skinparam backgroundColor #D3D3D3

component "Logstash" as Logstash
component "Fluentd" as Fluentd
component "Custom API" as CustomAPI
component "Beats" as Beats

component "Apache Kafka" as Kafka {
    note right of Kafka
      Real-time data stream processing
      High-throughput data transfer
      Connecting data sources and targets
    end note
}
component "Apache Spark" as Spark {
    note right of Spark
      Data processing and analysis
      Batch and stream processing capabilities
      Large-scale dataset processing
    end note
}

component "TensorFlow" as TensorFlow {
    note right of TensorFlow
      Deep learning and machine learning library
      Image recognition, natural language processing
      Recommendation systems, anomaly detection
    end note
}
component "Elasticsearch SQL" as ESSQL {
    note right of ESSQL
      Use SQL to query Elasticsearch
      Log analysis, business intelligence reporting
      Security analysis, real-time monitoring
    end note
}
component "Kibana" as Kibana
component "Grafana" as Grafana

database "Elasticsearch" {
    [Elasticsearch DB]
}

Beats --> Logstash : Collect logs
Logstash --> Kafka : Ingest logs
Fluentd --> Kafka : Ingest logs
CustomAPI --> Kafka : Ingest custom data

Kafka --> Spark : Stream data

Spark --> [Elasticsearch DB] : Process data &\nStore results

[Elasticsearch DB] --> TensorFlow : Source data for analysis
TensorFlow --> [Elasticsearch DB] : Store analysis results
[Elasticsearch DB] --> ESSQL : Query execution
ESSQL --> [Elasticsearch DB] : Store query results
Kibana -.-> [Elasticsearch DB] : Visualize data
Grafana -.-> [Elasticsearch DB] : Visualize data

@enduml
