@startuml

entity "Users" as U {
  *_id: ObjectId (PK)
  --
  username: String
  email: String
  password: String
}

entity "Events" as E {
  *_id: ObjectId (PK)
  --
  owner_id: ObjectId (FK to Users)
  event_name: String
  description: String
  start_time: Date
  end_time: Date
  recurrence_rule: String
  participants: Array<Participant>
}

entity "Participants" as P {
  *participant_id: ObjectId (PK)
  --
  event_id: ObjectId (FK to Events)
  user_id: ObjectId (FK to Users)
  status: String
}

entity "Reminders" as R {
  *_id: ObjectId (PK)
  --
  event_id: ObjectId (FK to Events)
  user_id: ObjectId (FK to Users)
  reminder_time: Date
}

note right of E
  Indexes:
  - owner_id: 1
  - start_time: 1, end_time: 1
  - event_name: "text", description: "text"
  Sharding Key:
  - owner_id: 1
end note

note right of R
    Indexes:
    - user_id: 1
    - event_id: 1
    Sharding Key:
    - user_id: 1
  end note

U ||--o{ E : creates
E ||--o{ P : includes
E ||--o{ R : has

@enduml
