@startuml
skinparam backgroundColor #D3D3D3
package "分布式文件系统" {
    node "客户端A" as ClientA
    node "客户端B" as ClientB
    node "名称节点" as NameNode {
        [元数据存储] as MetadataStorage
    }
    node "数据节点1" as DataNode1 {
        [数据存储] as DataStorage1
    }
    node "数据节点2" as DataNode2 {
        [数据存储] as DataStorage2
    }
    node "管理节点" as AdminNode
    node "负载均衡器" as LoadBalancer
    node "备份节点" as BackupNode

    ClientA -down-> LoadBalancer : 连接请求
    ClientB -down-> LoadBalancer : 连接请求
    LoadBalancer -right-> NameNode : 路由请求

    NameNode -down-> DataNode1 : 指派任务
    NameNode -down-> DataNode2 : 指派任务

    ClientA -right-> DataNode1 : 读/写数据
    ClientB -left-> DataNode2 : 读/写数据

    DataNode1 -down-> BackupNode : 数据备份
    DataNode2 -down-> BackupNode : 数据备份

    AdminNode -left-> NameNode : 管理与监控
    AdminNode -up-> DataNode1 : 管理与监控
    AdminNode -up-> DataNode2 : 管理与监控
}
@enduml
