@startuml
skinparam backgroundColor #D3D3D3

!define KafkaNode(x) class x << (K,orchid) >> 
!define PartitionNode(x) class x << (PT,green) >> 

package "Kafka Cluster" {
    KafkaNode(Broker1) 
    KafkaNode(Broker2) 
    KafkaNode(Broker3) 

    class Topic1 << (T,purple) >> 
    class Topic2 << (T,purple) >> 

    PartitionNode(Partition1_1) 
    PartitionNode(Partition1_2) 
    PartitionNode(Partition2_1) 
    PartitionNode(Partition2_2) 

    Topic1 -- Partition1_1 : contains
    Topic1 -- Partition1_2 : contains
    Topic2 -- Partition2_1 : contains
    Topic2 -- Partition2_2 : contains

    Partition1_1 -- Broker1 : held by
    Partition1_2 -- Broker2 : held by
    Partition2_1 -- Broker2 : held by
    Partition2_2 -- Broker3 : held by

    note right of Partition1_1 : Leader Replica
    note right of Partition1_2 : Follower Replica
    note right of Partition2_1 : Leader Replica
    note right of Partition2_2 : Follower Replica

    Partition1_1 -[hidden]> Partition1_2 : replicates to
    Partition1_2 -[hidden]> Partition1_1 : replicates to
    Partition2_1 -[hidden]> Partition2_2 : replicates to
    Partition2_2 -[hidden]> Partition2_1 : replicates to
}

@enduml
