@startuml
skinparam backgroundColor #E8E8E8

class Producer << (P,blue) >>
class Broker1 << (K,orchid) >>
class Broker2 << (K,orchid) >>
class Broker3 << (K,orchid) >>
class Consumer1 << (C,red) >>
class Consumer2 << (C,red) >>

Producer --> Broker1 : send
Broker1 --> Broker2 : replicate
Broker1 --> Broker3 : replicate
Broker1 --> Consumer1 : fetch
Broker2 --> Consumer2 : fetch

note top of Producer : 生产者发送消息到指定主题
note top of Broker1 : 消息被分区并复制到多个Broker
note top of Consumer1 : 消费者从Broker中获取消息

@enduml
