@startuml
skinparam backgroundColor #FFFAFA

class Broker1 << (K,orchid) >>
class Broker2 << (K,orchid) >>
class Broker3 << (K,orchid) >>
class Broker4 << (K,orchid) >>
class Zookeeper << (Z,yellow) >>

Broker1 --> Zookeeper : leader election
Broker2 --> Zookeeper : leader election
Broker3 --> Zookeeper : leader election

Broker1 -[#red]> Broker4 : fail
Broker2 -[#blue]> Broker4 : takeover
Broker3 -[#blue]> Broker4 : takeover

note top of Broker1 : 通过Zookeeper进行领导者选举和故障恢复
@enduml
