@startuml
skinparam backgroundColor #D3D3D3

package "Private Cloud Compute Nodes" {
    [Central Coordination Node] as Coordinator
    [Producer Node 1] as PrivateProducer1
    [Producer Node 2] as PrivateProducer2
    [Consumer Node 1] as PrivateConsumer1
    queue "Central Queue" as Queue
}

package "Free Compute Resources Nodes" {
    [Producer Node N] as FreeProducerN
    [Consumer Node M] as FreeConsumerM
}
    
[Thread API] as API

Coordinator --> PrivateProducer1 : Manage
Coordinator --> PrivateProducer2 : Manage
Coordinator --> PrivateConsumer1 : Manage
Coordinator --> Queue : Manage
    
PrivateProducer1 --> Queue : Put Strings
PrivateProducer2 --> Queue : Put Strings
FreeProducerN --> Queue : Put Strings

Queue --> PrivateConsumer1 : Get Strings
Queue --> FreeConsumerM : Get Strings

PrivateConsumer1 --> API : Validate String
FreeConsumerM --> API : Validate String

API --> Coordinator : Return Status Code

Coordinator -up-> [Stop Signal] : If Correct String Found

@enduml
